language: java
before_install:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "cp target/travis/settings.xml ~/.m2/settings.xml"

# whitelist
branches:
  only:
    - master

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

after_success:  mvn site --settings target/travis/settings.xml

env:
  global:
    - secure: "LO721rjYfnWYYVN+AxbcjWVLysN44Qt+ehGjl4WmKyrIp0gqhDc2PNtwykrM\n3vJy+I//YQy/m7f43B6qAh+KHY+ol0PCJ0Kcx1IAFZ1HR/yVaro04251sDKv\n3rwcFnqFAR9HEQmKGtCu5S9qLA/hIYDvt0oKWrlrT7N1knufoGY="    
    - secure: "Z1ehdzAP/BvyO+DiV8U7uQ/gd6QVrc00LCd+/MUKUAWC7N090Zue/X2TErsM\nBQ/FTR+9UmzpE7RqaHRZecjjq4GzhZGaZx4Yg/+ImiGusACmKDbO+FP8KdtI\nmhatnV3/7q4Fl7ttjbwsyDsLcSb/V+tO0o6l9FPlnup7kN2m3fo="
